# cell conditions
N : 20 # 80 Number of cells in the stack
Estack : 1 # Total voltage in V of a single stack
Feed : 2000 # Feed concentration (NaCL) in ppm
A : 0.0550 # Area of the membrane in m^2
T_tot : 60 # 120 Total time in min
km : 0.77E-3 # Mass transfer coefficient in m/s
Qdil : 0.75 # Dilution flow rate in m^3/hr
Qconc : 0.75 # Concentrated flow rate in m^3/hr
VT_dil : 0.3 # Volume of the dilute recirculation tank in m^3
VT_conc : 0.1 # Volume of the concentrated recirculation tank in m^3
Ldil : 6.0E-4 # Thickness of the dilute compartment in m
Lconc : 6.0E-4 # Thickness of the concentrated compartment in m
# membrane
Da : 3.28E-11 # Diffusion coefficient of NaCl in AEM 
Dc : 3.28E-11 # Diffusion coefficient of NaCl in CEM
ra : 29.0E-4 # Resistance of the AEM in ohm.m^2
rc : 24.0E-4 # Resistance of the CEM in ohm.m^2
permAEM : 1.0 # permselectivity of the AEM
permCEM : 1.0 # permselectivity of the CEM
La : 0.17E-3 # Length of the AEM in m
Lc : 0.17E-3 # Length of the CEM in m
phi : 0.92 # current efficieny